### ISSUE TITLE
Not sure why this is failing ... 

### ISSUE THREAD

**Issue by fir3pho3nixx** [ninject/Ninject.Extensions.Interception#36]
Tried: 

Implementing Ninject.Extensions.Interception.IInterceptor, easy enough called 'InstrumentationInterceptor'.

```csharp

public class InstrumentationInterceptor : IInterceptor
	{
		private static readonly ILog Log;

		static InstrumentationInterceptor()
		{
			Log = new RepositoryLoggingService().GetLogger(typeof(InstrumentationInterceptor));
		}

		private T TimeWrap<T>(string message, Func<T> function)
		{
			var stopWatch = Stopwatch.StartNew();

			var result = function();

			stopWatch.Stop();

			Log.Info($"{message}::{stopWatch.ElapsedMilliseconds}ms");

			return result;
		}

		public void Intercept(IInvocation invocation)
		{
			var message = $"Connect.Repository.Instrumentation -> {MethodSignatureFormatter.GetSignature(invocation.Request.Method, invocation.Request.Arguments)}";

			TimeWrap(message, () =>
			{
				invocation.Proceed();

				return invocation.ReturnValue;
			});
		}
	}


```

Then registering with:

```charp
Kernel.Bind<InstrumentationInterceptor>().ToSelf().InSingletonScope();

 Kernel.Bind(x => x
                .From(GetType().Assembly)
                .SelectAllClasses()
                .InNamespaceOf(GetType())
                .BindAllInterfaces()
				.Configure(c => c.Intercept(
					typeof(InstrumentationInterceptor),
					typeof(DatabaseWinsConcurrencyInterceptor))));


```

Ended up with:

[NullReferenceException]: Object reference not set to an instance of an object.
   at Ninject.Extensions.Interception.Advice.Advice.GetInterceptor(IProxyRequest request)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ninject.Extensions.Interception.Registry.AdviceRegistry.GetInterceptorsForRequest(IProxyRequest request)
   at Ninject.Extensions.Interception.Registry.AdviceRegistry.GetInterceptors(IProxyRequest request)
   at Ninject.Extensions.Interception.Wrapper.StandardWrapper.CreateInvocation(IProxyRequest request)
   at Ninject.Extensions.Interception.Wrapper.DynamicProxyWrapper.Intercept(IInvocation castleInvocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IAuthenticationRepositoryProxy.FindUser(String userName, String password)

**Comment by fir3pho3nixx** [comment]
Any idea's?

**Comment by fir3pho3nixx** [comment]
Closing this for now. Thanks.

**Comment by scott-xu** [comment]
You missed `With` function after `Configure`

**Comment by scott-xu** [comment]
The syntax is "intercept some types with some interceptors"

**Comment by fir3pho3nixx** [comment]
@scott-xu - thanks, this really was not obvious.
