### ISSUE TITLE
Factory and Interception

### ISSUE THREAD

**Issue by FrederickBrier** [ninject/Ninject.Extensions.Interception#50]
The problem appears to be an interaction or failure to interact between Ninject.Extensions.Interception and Ninject.Extensions.Factory. They work separately, but if you create an object using Factory interface and it is annotated with a C# attribute to proxy the constructed object with a proxy interceptor, it fails with an error:
```
2019-07-23T22:22:27.3407669Z Failed   SanityTest
2019-07-23T22:22:27.3418793Z Error Message:
2019-07-23T22:22:27.3419112Z  Initialization method MyDevice.Test.SmokeTest.TestInitialize threw exception. System.NotImplementedException: This is a DynamicProxy2 error: There are no interceptors specified for method 'ModelNameSpace.SetOfModels.ModelObject CreateModelObject()' which has no target. When calling method without target there is no implementation to 'proceed' to and it is the responsibility of the interceptor to mimic the implementation (set return value, out arguments etc).
2019-07-23T22:22:27.3419440Z Stack Trace:
2019-07-23T22:22:27.3419618Z     at Castle.DynamicProxy.AbstractInvocation.ThrowOnNoTarget()
2019-07-23T22:22:27.3419713Z    at Castle.DynamicProxy.Internal.CompositionInvocation.EnsureValidTarget()
2019-07-23T22:22:27.3419823Z    at Castle.Proxies.Invocations.IModelFactory_CreateModelObject.InvokeMethodOnTarget()
2019-07-23T22:22:27.3420072Z    at Castle.DynamicProxy.AbstractInvocation.Proceed()
2019-07-23T22:22:27.3420161Z    at Castle.Proxies.IModelFactoryProxy.CreateModelObject()
2019-07-23T22:22:27.3420473Z    at MyDevice.ConfigurationFactory.MyDeviceControl..ctor(IModelFactory ModelFactory, String dutUri) in D:\Agent_1\_work\8\s\TestToolbox\MyDevice\ConfigurationFactory\MyDeviceControl.cs:line 85
2019-07-23T22:22:27.3421003Z    at MyDevice.Test.SmokeTest.TestInitialize() in D:\Agent_1\_work\8\s\TestToolbox\MyDevice.Test\SmokeTest.cs:line 90
2019-07-23T22:22:27.3421220Z 
2019-07-23T22:22:27.3429234Z Standard Output Messages:
2019-07-23T22:22:27.3429441Z  Creating a new T-Rex Helper for URI: 'http://10.15.128.54:32011'
2019-07-23T22:22:27.3429606Z  Setting the Helper timeout to 120000 milliseconds. 
```
Is there some syntactic sugar to make this work? Or is this a bug? Or as yet unimplemented feature?

This is cross posted to the [Factory project](https://github.com/ninject/Ninject.Extensions.Factory/issues/48). It may be a team effort :), and based on the responses, I would be glad to fork and take a SWAG at it if code changes are needed..

**Comment by FrederickBrier** [comment]
This user error was caused because the interceptor needs a default constructor, as it extends the class, but does not use the constructor parameters. Ninject will use the constructor with the most parameters it can resolve, so this is perfectly fine solution.
